export const AXIOS_ORDERS = 'AXIOS_ORDERS';
export const AXIOS_ORDERS_SUCCESS = 'AXIOS_ORDERS_SUCCESS';
export const AXIOS_ORDERS_FAILURE = 'AXIOS_ORDERS_FAILURE';

export const AXIOS_ORDER_ITEMS = 'AXIOS_ORDER_ITEMS';
export const AXIOS_ORDER_ITEMS_SUCCESS = 'AXIOS_ORDER_ITEMS_SUCCESS';
export const AXIOS_ORDER_ITEMS_FAILURE = 'AXIOS_ORDER_ITEMS_FAILURE';